package: yform_mediafile
version: '0.0.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/addon_key
requires:
    redaxo: '^5.13.0'
    packages:
        yform: '>=4'
    php:
        version: '>=7.3, <9'
