package: yform_mediafile
version: '1.1.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_mediafile
requires:
    redaxo: '^5.13.0'
    packages:
        yform: '>=4'
    php:
        version: '>=7.3, <9'
